### ISSUE TITLE
BUG: github_user_repos languages link 404

### ISSUE THREAD

**Issue by westurner** [resume/resume.github.com#196]
Steps to reproduce:

1. Click on a language link "Scheme"
2. 404: https://github.com/languages/Scheme

Source:

* https://github.com/resume/resume.github.com/blob/master/js/githubresume.js#L303

Solution:

A. TODO: find a current link for each language
B.

**Comment by u2** [comment]
This has been fixed by #219

**Comment by westurner** [comment]
Thanks!
