### ISSUE TITLE
HTTPS loading is broken

### ISSUE THREAD

**Issue by lehitoskin** [resume/resume.github.com#203]
Going to https://resume.github.io loads an empty web page.

Steps to produce:
1. Open Firefox
2. Enter in the URL
3. ???
4. Sadness

Reproducible:
Always

**Comment by gdude2002** [comment]
Likewise in Chrome.

```
Mixed Content: The page at 'https://resume.github.io/' was loaded over HTTPS, but requested an insecure stylesheet 'http://yui.yahooapis.com/2.7.0/build/reset-fonts-grids/reset-fonts-grids.css'. This request has been blocked; the content must be served over HTTPS.

resume.github.io/:1 Mixed Content: The page at 'https://resume.github.io/' was loaded over HTTPS, but requested an insecure script 'http://code.jquery.com/jquery-1.8.1.min.js'. This request has been blocked; the content must be served over HTTPS.

githubresume.js:17 Uncaught ReferenceError: $ is not defined
    (anonymous function) @ githubresume.js:17
```

The solution is, of course, twofold:

1. Find a CDN for your assets that supports https, or host them yourself
2. Use relative protocol urls starting with `//` instead of `http` or `https`

**Comment by dodekeract** [comment]
Could the be fixed? This site is unusable with HTTPS everywhere.

**Comment by u2** [comment]
Duplicate issue #182 .
There are two many same issues and PR, it make me confused, so I will close this.
