### ISSUE TITLE
But I have though

### ISSUE THREAD

**Issue by istx25** [resume/resume.github.com#206]
<img width="1079" alt="screen shot 2015-08-05 at 2 35 21 pm" src="https://cloud.githubusercontent.com/assets/6799989/9086886/3ea7181a-3b7f-11e5-9e44-b35a6587a6e2.png">

**Comment by mar77i** [comment]
Same for me.
Something is broken indeed, which is inconvenient as I started using the URL...

**Comment by u2** [comment]
I don't think this is a bug.Like this `https://github.com/search?utf8=%E2%9C%93&q=user%3Adhh` and `https://github.com/search?utf8=%E2%9C%93&q=user%3Adhh/`.
`istx25/` is a valid name as a parameter.
