### ISSUE TITLE
Display emoji in repository descriptions

### ISSUE THREAD

**Issue by honzi** [resume/resume.github.com#210]
There are many repositories that include emoji in their descriptions. However, these emoji don't get displayed on résumés and the substituted text makes the descriptions look a lot less "professional". Résumés should display correct emoji.

An example can be found on my résumé: http://resume.github.io/?honzi

**Comment by simplyianm** [comment]
https://assets-cdn.github.com/images/icons/emoji/<emoji>.png

**Comment by u2** [comment]
Yes. It's a bug. So anyone want to help on this?

**Comment by aldahick** [comment]
#228 should fix this.
