### ISSUE TITLE
Dear resume.github.com

### ISSUE THREAD

**Issue by u2** [resume/resume.github.com#216]
Is this project no longer maintained?
I am very interested in this project.I think github resume is a really great idea, but there are also many issues to resolve.According to the PR and issues,there are some developers with great enthusiasm for this project.And I have read some issues and PR, some are valuable.So may I be the member of this project?I think we could find some members for going on.

Thanks.

**Comment by NumEricR** [comment]
You should ask @davidcoallier?! :)

**Comment by davidcoallier** [comment]
Unfortunately not maintained anymore, I just don't have the time. Apologies for this, 

If you both want to take over I'll add you there :)

P.S. Just saw 22 pull requests :O

**Comment by u2** [comment]
Ok. It's a pleasure to joining in. :smile:

**Comment by u2** [comment]
@davidcoallier Bump!

**Comment by davidcoallier** [comment]
Apologies, I'm travelling a lot at the moment and connectivity is reduced. Adding you now :)

**Comment by davidcoallier** [comment]
You have been added as a collaborator! Enjoy and good luck!
