### ISSUE TITLE
Not all commits are appearing as contributions

### ISSUE THREAD

**Issue by rs2** [resume/resume.github.com#242]
E.g. https://github.com/pandas-dev/pandas/pull/12909

**Comment by stuntguy3000** [comment]
Would/should **closed** contributions even count?

**Comment by rs2** [comment]
@stuntguy3000 In what sense closed? :)

**Comment by stuntguy3000** [comment]
![image](https://cloud.githubusercontent.com/assets/1522389/22850188/73d78614-f055-11e6-855c-ecfae9dafff1.png)

This PR **was not merged**. If people use git in stupid ways like this, then unfournatly I don't think it can be too easy to detect that its your contribution.

**Comment by rs2** [comment]
@stuntguy3000 You are right. Until now I thought that my commits were merged as a result of my PR.

**Comment by stuntguy3000** [comment]
Indeed I am ;)
